# Generated by Django 2.1.7 on 2019-04-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190415_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.PositiveIntegerField(null=True, verbose_name='Phone Number'),
        ),
    ]
