# Generated by Django 2.1.7 on 2019-04-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%M/%D/'),
        ),
    ]
