# Generated by Django 2.1.7 on 2019-04-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190430_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'product type'},
        ),
    ]
